#
# Copyright (c) 2017, 2020 ADLINK Technology Inc.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#
# Contributors:
#   ADLINK zenoh team, <zenoh@adlink-labs.tech>
#

before_install:
  - sudo apt-get install -y libssl1.0.0 libev4
  - sudo curl -L -o /usr/local/lib/libzenohc.so https://github.com/atolab/atobin/raw/master/zenoh-c/unstable/ubuntu/18.04/libzenohc.so
  - sudo apt install -y python3-pip
addons:
  apt:
    update: true
dist: bionic
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
env:
  matrix:
  - TOXENV=py3
  - TOXENV=pep8

install:
  - travis_retry pip install tox
  - pip install flake8
  - pip install codecov
  - pip install mvar
script:
  - bash -ex .travis-ci.sh
cache:
  directories:
    - $HOME/.cache/pip
after_success:
- codecov
